server:
  port: 8083
dubbo:
  application:
    name: web_item
  registry:
    address: zookeeper://192.168.245.199:2181
  consumer:
    timeout: 10000
    retries: 0
spring:
  rabbitmq:
    host: 192.168.245.199
    virtual-host: /