spring:
  datasource:
    url: jdbc:mysql:///shop
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: 192.168.245.199
    password: root
dubbo:
  application:
    name: service_cart
  registry:
    address: zookeeper://192.168.245.199:2181
  protocol:
    port: -1
    name: dubbo
  consumer:
    check: false
    timeout: 10000
    retries: 0
