server:
  port: 8086
spring:
  thymeleaf:
    cache: false
  redis:
    host: 192.168.245.199
    password: root
dubbo:
  application:
    name: web_order
  registry:
    address: zookeeper://192.168.245.199:2181
  consumer:
    check: false
    timeout: 10000
    retries: 0