spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/shop
dubbo:
  application:
    name: service_goods
  registry:
    address: zookeeper://192.168.245.199:2181
  protocol:
    port: -1
  consumer:
    check: false
    timeout: 10000
    retries: 3