spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql:///shop
dubbo:
  application:
    name: service_user
  registry:
    address: zookeeper://192.168.245.199:2181
  protocol:
    port: -1
    name: dubbo
