server:
  port: 8080
spring:
  thymeleaf:
    cache: false
dubbo:
  application:
    name: web_back
  registry:
    address: zookeeper://192.168.245.199:2181
  consumer:
    check: false
    timeout: 10000
    retries: 3