server:
  port: 8080
spring:
  thymeleaf:
    cache: false
  servlet:
    multipart:
      #限制文件上传的大小
      max-file-size: 20MB
      max-request-size: 20MB
dubbo:
  application:
    name: web_back
  registry:
    address: zookeeper://192.168.245.199:2181
  consumer:
    check: false
    timeout: 10000
    retries: 0

#自定义一个文件上传路径
upload:
  path: C:/Users/Administrator/Desktop/sz_java_1903/image/
#配置分布式文件系统
fdfs:
  so-timeout: 10000
  connect-timeout: 10000
  tracker-list:
    - 192.168.245.199:22122
  thumb-image:
    width: 100
    height: 100
  pool:
    jmx-enabled: false