server:
  port: 8080
spring:
  thymeleaf:
    cache: false
  servlet:
    multipart:
      #限制文件上传的大小
      max-file-size: 20MB
      max-request-size: 20MB
dubbo:
  application:
    name: web_back
  registry:
    address: zookeeper://192.168.245.199:2181
  consumer:
    check: false
    timeout: 10000
    retries: 3

#自定义一个文件上传路径
upload:
  path: C:/Users/Administrator/Desktop/sz_java_1903/image/